name: husn_al_muslim
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter



  cupertino_icons: ^1.0.5
  shared_preferences: ^2.1.1
  path: ^1.8.3
  path_provider: ^2.0.15
  dio: ^5.1.2
  quiver: ^3.2.1
  #  event_bus: ^2.0.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  theme_provider: ^0.6.0
  sqflite: ^2.2.8+4
  sqflite_common_ffi: ^2.2.5
  equatable: ^2.0.5
  flutter_svg: ^2.0.6
  responsive_builder: ^0.7.0
  desktop_window: ^0.4.0
  another_xlider: ^3.0.1
  http: ^0.13.6
  lottie: ^2.3.2
  hijri: ^3.0.0
  dropdown_button2: ^2.1.3
  arabic_numbers: ^1.0.0
  flutter_sliding_up_panel: ^2.0.1
  flutter_staggered_animations: ^1.1.1
  share_plus: ^6.3.4
  clipboard: ^0.1.3
  #  app_rename: ^0.0.1
  get: ^4.6.5
  audioplayers: ^4.0.1
  wakelock: ^0.6.1+1
  square_percent_indicater: ^0.1.0
  group_button: ^5.3.0
  scrollable_positioned_list: ^0.3.8
  url_launcher: ^6.1.11
  rate_my_app: ^2.0.0
  smooth_page_indicator: ^1.1.0
  bot_toast: ^4.0.4
  home_widget: ^0.2.1
  workmanager: ^0.5.1
  connectivity_plus: ^4.0.1
  animated_toggle_switch: ^0.6.2
  flutter_local_notifications: ^14.1.0
  flutter_native_timezone_updated_gradle: ^2.0.3
  day_night_time_picker: ^1.2.0+2
  html: ^0.15.3
  package_rename: ^1.3.0
  anim_search_bar: ^2.0.3
  painter: ^2.0.0
  image_gallery_saver: ^2.0.2
  image: ^4.0.17
  easy_image_viewer: ^1.2.0
  intl: any
  stylish_bottom_bar: ^1.0.2
  carousel_slider: ^4.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  flutter_native_splash: ^2.2.15

flutter_native_splash:
  color: "#263A29"
  color_dark: "#263A29"
  image: assets/app_icon.png
  image_dark: assets/app_icon.png

  android_12:
    image: assets/ic_launcher.png
    icon_background_color: "#263A29"
    image_dark: assets/ic_launcher.png
    icon_background_color_dark: "#263A29"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  generate: true
  uses-material-design: true

  assets:
    - assets/onboarding/
    - assets/images/
    - assets/lottie/
    - assets/share_images/
    - assets/app_icon.png
    - assets/svg/
    - assets/svg/hijri/
    - assets/svg/surah_name/
    - assets/books/


  fonts:
    - family: uthmanic
      fonts:
        - asset: assets/fonts/UthmanTN1_Ver10.otf

    - family: uthmanic2
      fonts:
        - asset: assets/fonts/UthmanicHafs_V20.ttf

    - family: kufi
      fonts:
        - asset: assets/fonts/Kufam-Italic-VariableFont_wght.ttf
          style: italic
        - asset: assets/fonts/Kufam-VariableFont_wght.ttf
          weight: 500
        - asset: assets/fonts/Kufam-Regular.ttf
          weight: 100

    - family: naskh
      fonts:
        - asset: assets/fonts/NotoNaskhArabic-VariableFont_wght.ttf

    - family: vexa
      fonts:
        - asset: assets/fonts/VEXA.ttf
          weight: 800
        - asset: assets/fonts/VEXA-light.ttf
          weight: 500
        - asset: assets/fonts/VEXA-ITALIC.ttf
          style: italic
