name: Azkary
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.3+4

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter



  cupertino_icons: ^1.0.5
  shared_preferences: ^2.1.1
  path: ^1.8.3
  path_provider: ^2.0.15
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  theme_provider: ^0.6.0
  sqflite: ^2.2.8+4
  sqflite_common_ffi: ^2.2.5
  flutter_svg: ^2.0.6
  responsive_builder: ^0.7.0
  desktop_window: ^0.4.0
  another_xlider: ^3.0.1
  http: ^1.1.0
  lottie: ^2.3.2
  hijri: ^3.0.0
  dropdown_button2: ^2.1.3
  arabic_numbers: ^1.0.0
  flutter_staggered_animations: ^1.1.1
  share_plus: ^7.0.2
  clipboard: ^0.1.3
  get: ^4.6.5
  url_launcher: ^6.1.11
  rate_my_app: ^2.0.0
  bot_toast: ^4.0.4
  animated_toggle_switch: ^0.7.0
  flutter_local_notifications: ^15.1.0+1
  flutter_timezone: ^1.0.7
  day_night_time_picker: ^1.2.0+2
  package_rename: ^1.3.3
  painter: ^2.0.0
  image_gallery_saver: ^2.0.2
  image: ^4.0.17
  easy_image_viewer: ^1.2.0
  stylish_bottom_bar: ^1.0.2
  carousel_slider: ^4.2.1
  cupertino_onboarding: ^1.1.1
  flutter_slider_drawer: ^2.1.3
  in_app_review: ^2.0.6
  horizontal_stepper_step: ^0.0.5
  flutter_screenutil: ^5.8.4
  package_info_plus: ^4.0.2
  device_info_plus: ^9.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  flutter_native_splash: ^2.2.15

flutter_native_splash:
  color: "#F5EFE7"
  color_dark: "#263A29"
  image: assets/app_icon.png
  image_dark: assets/app_icon.png

  android_12:
    image: assets/app_icon.png
    icon_background_color: "#F5EFE7"
    image_dark: assets/app_icon.png
    icon_background_color_dark: "#263A29"

package_rename_config:
  android:
    app_name: Athkary
    package_name: com.alheekmah.azkaryapp

  ios:
    app_name: Athkary
    package_name: com.alheekmah.azkaryapp

  macos:
    app_name: Athkary
    package_name: com.alheekmah.azkaryapp


  flutter_lints: ^2.0.0


flutter:

  generate: true
  uses-material-design: true

  assets:
    - assets/onboarding/
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/share_images/
    - assets/app_icon.png
    - assets/svg/
    - assets/svg/hijri/
    - assets/svg/surah_name/
    - assets/books/


  fonts:
    - family: uthmanic
      fonts:
        - asset: assets/fonts/UthmanTN1_Ver10.otf

    - family: uthmanic2
      fonts:
        - asset: assets/fonts/UthmanicHafs_V20.ttf

    - family: kufi
      fonts:
        - asset: assets/fonts/Kufam-Italic-VariableFont_wght.ttf
          style: italic
        - asset: assets/fonts/Kufam-VariableFont_wght.ttf
          weight: 500
        - asset: assets/fonts/Kufam-Regular.ttf
          weight: 100

    - family: naskh
      fonts:
        - asset: assets/fonts/NotoNaskhArabic-VariableFont_wght.ttf

    - family: vexa
      fonts:
        - asset: assets/fonts/VEXA.ttf
          weight: 800
        - asset: assets/fonts/VEXA-light.ttf
          weight: 500
        - asset: assets/fonts/VEXA-ITALIC.ttf
          style: italic
